services:
  - type: web
    name: earthsafe-backend
    env: node
    rootDirectory: backend
    region: frankfurt
    plan: free
    buildCommand: npm install && npm run build
    startCommand: npm start
    branch: main
    envVars:
      - key: NODE_VERSION
        value: 20.11.0
      - key: JWT_SECRET
        generateValue: true
      - key: MONGODB_URI
        sync: false
